### ISSUE TITLE
IndexError: list index out of range when trying step 2

### ISSUE THREAD

**Issue by michaelpulis** [wendru18/citation-network#1]
I cannot understand what I did that caused this to happen
![image](https://user-images.githubusercontent.com/35961035/99975813-f8f9bb80-2da2-11eb-8a6a-9af5d63a843f.png)

**Comment by andaqu** [comment]
Hi @michaelpulis . That error was as a result of attempting to draw an empty citation network. This issue is now solved with the below code. 

``` python
    try:
        app = Viewer(DG)
        app.mainloop()
    except IndexError:
        print("(!) Citation network is empty. Try adding more papers...")
```

**Comment by michaelpulis** [comment]
I would launch an internal inquiry to find out why this was not part of the original codebase.... Thank you anyways...
